import Link from "next/link";
import { MetricCard } from "@/components/metric-card";
import { requireSession } from "@/lib/auth/current-session";
import { getAnalytics } from "@/lib/domain/operations-service";

export default async function AnalyticsPage({ searchParams }: { searchParams:Promise<{period?:string}> }) {
  const [session,query]=await Promise.all([requireSession(),searchParams]); const data=await getAnalytics(session.tenantId); const period=["7","30","90"].includes(query.period ?? "") ? query.period! : "30";
  return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">ANALYTICS</p><h1>Rendimiento comercial</h1><p>Datos calculados directamente desde tu espacio de trabajo.</p></div><div className="segmented">{["7","30","90"].map((days)=><Link className={period===days ? "active" : ""} href={`/analytics?period=${days}`} key={days}>{days} días</Link>)}</div></header><section className="metrics-grid four"><MetricCard icon="♙" tone="blue" label="Clientes" value={String(data.clients)} detail="cartera total"/><MetricCard icon="↗" tone="violet" label="Pipeline" value={data.pipeline} detail={`${data.opportunities} oportunidades`}/><MetricCard icon="⌁" tone="green" label="Forecast" value={data.forecast} detail="ponderado por probabilidad"/><MetricCard icon="◔" tone="orange" label="Conversión" value={`${data.conversion}%`} detail={`${data.quotes} presupuestos`}/></section><section className="analytics-grid"><article className="panel analytics-card"><p className="eyebrow">FACTURACIÓN</p><h2>{data.invoiced}</h2><div className="comparison-bars"><div><span style={{width:"78%"}}/><b>Cobrado {data.collected}</b></div><div className="danger"><span style={{width:"24%"}}/><b>Vencido {data.overdue}</b></div></div></article><article className="panel analytics-card"><p className="eyebrow">PRODUCTIVIDAD</p><h2>{data.pendingTasks} tareas pendientes</h2><div className="donut compact"><div><strong>{data.completedTasks}</strong><span>completadas</span></div></div></article></section></main>;
}
