import Link from 'next/link';import {notFound} from 'next/navigation';import {z} from 'zod';
import {requireSession} from '@/lib/auth/current-session';import {can} from '@/lib/security/rbac';import {listClients,getClient} from '@/lib/domain/crm-service';import {listInput,ApiError} from '@/lib/api/contracts';import {saveClientAction,archiveClientAction} from '@/app/crm-actions';import {SubmitButton} from '@/components/submit-button';import {PageFeedback} from '@/components/page-feedback';
export default async function Clients({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const [session,q]=await Promise.all([requireSession(),searchParams]);const parsed=listInput.safeParse({q:q.q??'',page:q.page??'1'});const filters=parsed.success?parsed.data:listInput.parse({});const rows=await listClients(session,filters);const editable=can(session.role,'crm:write');
 let selected:Awaited<ReturnType<typeof getClient>>|undefined;
 if(q.editar){if(!z.uuid().safeParse(q.editar).success)notFound();try{selected=await getClient(session,q.editar);}catch(e){if(e instanceof ApiError&&e.status===404)notFound();throw e;}}
 const formVisible=editable&&(q.nuevo==='1'||!!selected);
 return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">RELACIONES COMERCIALES</p><h1>Clientes</h1><p>Contexto, seguimiento y datos de cada relación, en un único lugar.</p></div>{editable?<Link href="/clientes?nuevo=1" className="primary-button button-link">Nuevo cliente</Link>:null}</header><PageFeedback error={q.error} success={q.guardado?'Cliente guardado.':q.archivado?'Cliente archivado. Sus facturas y conversaciones se conservan.':undefined}/>
 <section className="panel"><form className="filter-form" role="search"><label>Buscar clientes<input name="q" type="search" maxLength={100} defaultValue={filters.q} placeholder="Nombre, empresa o correo"/></label><button className="secondary-button">Buscar</button></form><p>{rows.pagination.total} clientes activos en el listado</p><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Empresa</th><th>Correo</th><th>Estado</th><th>Valor potencial</th><th>Acciones</th></tr></thead><tbody>{rows.data.map(c=><tr key={c.id}><td><strong>{c.name}</strong><p className="helper-text">{c.phone}</p></td><td>{c.company}</td><td>{c.email}</td><td><span className="badge">{c.status}</span></td><td>{new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(c.value))}</td><td>{editable?<Link href={'/clientes?editar='+c.id}>Editar</Link>:'Solo lectura'}</td></tr>)}</tbody></table></div>{!rows.data.length?<div className="empty-state"><strong>No hay clientes para esta búsqueda</strong><p>Prueba otro término o añade tu primer cliente.</p></div>:null}<nav className="pagination" aria-label="Páginas de clientes">{filters.page>1?<Link href={'/clientes?q='+encodeURIComponent(filters.q)+'&page='+(filters.page-1)}>Anterior</Link>:null}<span>Página {filters.page}</span>{filters.page*filters.limit<rows.pagination.total?<Link href={'/clientes?q='+encodeURIComponent(filters.q)+'&page='+(filters.page+1)}>Siguiente</Link>:null}</nav></section>
 {formVisible?<article className="panel account-panel" id="editor"><div className="panel-heading"><h2>{selected?'Editar cliente':'Nuevo cliente'}</h2><Link href="/clientes">Cerrar editor</Link></div><form action={saveClientAction} className="form-grid"><input type="hidden" name="id" value={selected?.id??''}/><input type="hidden" name="version" value={selected?.version??''}/><label>Nombre<input name="name" required minLength={2} maxLength={120} defaultValue={selected?.name}/></label><label>Empresa<input name="company" required minLength={2} maxLength={160} defaultValue={selected?.company}/></label><label>Correo<input name="email" type="email" required maxLength={200} defaultValue={selected?.email}/></label><label>Teléfono<input name="phone" type="tel" maxLength={40} defaultValue={selected?.phone}/></label><label>Valor potencial<input name="value" inputMode="decimal" required defaultValue={selected?.value??'0'}/></label><label>Estado<select name="status" defaultValue={selected?.status??'Potencial'}><option>Potencial</option><option>Activo</option><option>Inactivo</option></select></label><div className="wide"><SubmitButton>Guardar cliente</SubmitButton></div></form>{selected?<details className="archive-panel"><summary>Archivar este cliente</summary><p>Sale del listado y de nuevas selecciones. Conservamos sus relaciones e historial.</p><form action={archiveClientAction}><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="version" value={selected.version}/><label className="check-row"><input type="checkbox" name="confirm" required/>Confirmo que quiero archivarlo</label><SubmitButton>Archivar cliente</SubmitButton></form></details>:null}</article>:null}</main>;
}

