'use client';
import {useState} from 'react';
import Link from 'next/link';
import {InvoiceShowcase,InvoiceServices} from './invoice-showcase';

const plans=[
  {name:'Starter',price:29,max:5,messages:'1.000',tag:'Poner orden. Empezar a crecer.',description:'Para profesionales y equipos pequeños que quieren dar seguimiento a cada oportunidad.',features:['Clientes y oportunidades','Presupuestos y tareas','Seguimiento por email y WhatsApp','Hasta 5 personas en el equipo'],future:'Firma digital y ampliación de integraciones'},
  {name:'Pro',price:79,max:20,messages:'5.000',tag:'Tu equipo, un paso por delante.',description:'Para combinar organización, automatización y borradores con IA en el trabajo diario.',features:['Todo lo esencial de Starter','Borradores de seguimiento con IA','Más capacidad de mensajería','Hasta 20 personas en el equipo'],future:'Plantillas ampliadas y servicios adicionales'},
  {name:'Business',price:149,max:50,messages:'15.000',tag:'Más capacidad para crecer juntos.',description:'Para operaciones comerciales con más personas, más conversaciones y más volumen.',features:['IA y seguimiento automatizado','Mayor cupo de mensajes','Gestión de roles y auditoría','Hasta 50 personas en el equipo'],future:'Predicción comercial e informes personalizados'},
  {name:'Enterprise',price:299,max:100000,messages:'Sin límite mensual de plan',tag:'Una operación a tu medida.',description:'Para organizaciones que necesitan definir una implantación y un alcance específicos.',features:['Licencias según contratación','Sin cupo mensual de mensajes del plan','Permisos y auditoría','Alcance de implantación a definir'],future:'SSO, entorno dedicado y acuerdos de servicio'},
] as const;
const services=[
  {n:'01',title:'Tu cliente. Su historia.\nTodo conectado.',text:'Clientes, oportunidades, presupuestos y tareas relacionados para saber qué ha pasado y qué toca hacer.',icon:'people'},
  {n:'02',title:'El seguimiento deja\nde depender de la memoria.',text:'Organiza tus próximas acciones y prepara reglas de inactividad que convierten presupuestos pendientes en tareas concretas.',icon:'flow'},
  {n:'03',title:'Menos página en blanco.\nMás criterio comercial.',text:'Prepara borradores con IA a partir del contexto de una oportunidad. Tu equipo revisa y decide qué enviar.',icon:'spark'},
];
function Icon({name='arrow'}:{name?:string}){
  const shapes:Record<string,React.ReactNode>={arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,check:<path d="m5 12 4 4L19 6"/>,people:<><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2m2-15a3 3 0 0 1 0 6m2 3a5 5 0 0 1 2 4v2"/></>,flow:<><rect x="3" y="3" width="6" height="6" rx="1.5"/><rect x="15" y="15" width="6" height="6" rx="1.5"/><path d="M9 6h6a3 3 0 0 1 3 3v6M6 9v9h9"/></>,spark:<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>,shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,chart:<path d="M4 20V10m8 10V4m8 16V7"/>};
  return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{shapes[name]??shapes.arrow}</svg>;
}
function Brand(){return <span className="mkt-brand"><span className="mkt-symbol">R</span>Revenia<span className="mkt-brand-dot">.</span></span>;}
export function MarketingSite(){
  const [selected,setSelected]=useState(1),[annual,setAnnual]=useState(false),[seats,setSeats]=useState(1),[view,setView]=useState('Pipeline'),[followup,setFollowup]=useState(false),[draft,setDraft]=useState(false);
  const plan=plans[selected]!;
  const money=(value:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value);
  function selectPlan(index:number,scroll=false){setSelected(index);setSeats(n=>Math.min(n,plans[index]!.max));setFollowup(false);setDraft(false);if(scroll)document.getElementById('demo')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
  return <div className="mkt"><a className="mkt-skip" href="#contenido">Ir al contenido</a>
    <header className="mkt-header"><div className="mkt-nav"><a href="#" aria-label="Revenia, inicio"><Brand/></a><nav aria-label="Navegación de la web"><a href="#producto">Producto</a><a href="#servicios">Servicios</a><a href="#planes">Planes</a><a href="#seguridad">Seguridad</a></nav><div className="mkt-nav-actions"><Link href="/login" className="mkt-login">Iniciar sesión</Link><a className="mkt-button mkt-button-small" href="#demo">Explorar demo <Icon/></a></div><details className="mkt-mobile-menu" onClick={event=>{if(event.target instanceof Element && event.target.closest('a')) event.currentTarget.open=false;}}><summary>Menú</summary><a href="#producto">Producto</a><a href="#servicios">Servicios</a><a href="#planes">Planes</a><a href="#demo">Explorar demo</a><Link href="/login">Iniciar sesión</Link></details></div></header>
    <main id="contenido"><section className="mkt-hero"><div className="mkt-hero-glow"/><div className="mkt-container mkt-hero-content"><p className="mkt-pill"><span/> FACTURAS · COBROS · AUTOMATIZACIÓN</p><h1>Menos perseguir<br/>facturas.<br/><em>Más hacer crecer<br/>tu negocio.</em></h1><p className="mkt-hero-description">Organiza facturas, prepara el seguimiento de cobros y recupera presupuestos. Todo conectado a tus clientes, en un espacio de trabajo claro.</p><div className="mkt-actions"><a className="mkt-button" href="#demo">Ver cómo funciona <Icon/></a><a className="mkt-button mkt-button-outline" href="#planes">Encuentra tu plan</a></div><p className="mkt-hero-note">Web en preparación · Explora sin contratar ni realizar pagos</p><div className="mkt-hero-product"><InvoiceShowcase/><div className="mkt-floating-note"><span><Icon name="check"/></span><div><strong>Cada cobro, con contexto.</strong><small>Tu equipo mantiene el control.</small></div></div></div></div></section>
    <InvoiceServices/><section className="mkt-sectors mkt-container" aria-label="Sectores"><p>PARA NEGOCIOS QUE CRECEN CON CADA CLIENTE</p><div><span>Estudios & agencias</span><span>Reformas & instalaciones</span><span>Servicios profesionales</span><span>Distribución & ventas</span></div></section>
    <section className="mkt-section mkt-container" id="producto"><div className="mkt-section-heading"><div><p className="mkt-eyebrow">EL CRM QUE CONECTA VENTAS Y ADMINISTRACIÓN</p><h2>Una venta no acaba<br/>al enviar la propuesta.</h2></div><p>Del primer contacto al estado de cobro: organiza el trabajo de tu equipo y prepara automatizaciones alrededor de cada cliente.</p></div><div className="mkt-service-grid">{services.map(s=><article className="mkt-service-card" key={s.n}><div className="mkt-card-top"><span className="mkt-icon-box"><Icon name={s.icon}/></span><small>{s.n}</small></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section className="mkt-workflow" id="servicios"><div className="mkt-container mkt-workflow-grid"><div><p className="mkt-eyebrow">TODO CONECTADO AL TRABAJO DE TU EQUIPO</p><h2>Del presupuesto<br/><em>al cobro, con orden.</em></h2><p>Revenia reúne la gestión comercial, el seguimiento y el estado de tus facturas. Tú conservas el contexto; tu equipo gana foco.</p><a href="#demo" className="mkt-text-link">Mira cómo encaja en tu día <Icon/></a></div><div className="mkt-flow-list">{[['01','Conoce a tu cliente','Centraliza contactos, conversaciones y oportunidades.'],['02','Da forma a la propuesta','Organiza presupuestos, importes y próximas acciones.'],['03','Mantén la conversación','Prepara seguimientos y revisa borradores antes de enviarlos.'],['04','Sigue el resultado','Consulta el estado comercial, las facturas y los cobros.']].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><Icon/></div>)}</div></div><div className="mkt-container mkt-connections"><span>Conexiones en preparación para el lanzamiento</span><div><b>Email</b><b>WhatsApp Business</b><b>Stripe</b><b>IA</b></div><small>Adaptadores implementados; validación con cuentas reales pendiente.</small></div></section>
    <section className="mkt-section mkt-container" id="demo"><div className="mkt-section-heading"><div><p className="mkt-eyebrow">UN MISMO CRM. DISTINTAS CAPACIDADES.</p><h2>Encuentra tu forma<br/>de trabajar.</h2></div><p>Alterna entre planes y prueba esta vista ilustrativa. Cambian los cupos y la disponibilidad de IA; tus datos y tu suscripción reales permanecen intactos.</p></div><div className="mkt-plan-tabs" role="group" aria-label="Plan de la demostración">{plans.map((p,i)=><button key={p.name} aria-pressed={selected===i} onClick={()=>selectPlan(i)}>{p.name}<span>{i===0?'Esencial':i===1?'Con IA':i===2?'Más capacidad':'A medida'}</span></button>)}</div>
      <div className="mkt-interactive"><div className="mkt-preview-header"><div><span className="mkt-preview-icon"><Icon name="chart"/></span><div><h3>Tu espacio {plan.name}</h3><p>Estudio Norte · Vista ilustrativa con datos ficticios</p></div></div><span className="mkt-preview-chip">{selected===3?'Licencias según contratación':`Hasta ${plan.max} personas`}</span></div><div className="mkt-preview-stats"><div><small>Mensajes / mes</small><strong>{plan.messages}</strong></div><div><small>Borradores con IA</small><strong>{selected===0?'No incluidos':'Incluidos'}</strong></div><div><small>Seguimiento creado en la demo</small><strong>{followup?'1 tarea':'Sin tareas nuevas'}</strong></div></div><div className="mkt-preview-nav" role="group" aria-label="Sección de la demostración">{['Pipeline','Seguimientos','IA'].map(v=><button aria-pressed={view===v} key={v} onClick={()=>setView(v)}>{v}</button>)}</div>
      <div className="mkt-preview-content">{view==='Pipeline'?<div className="mkt-kanban">{[['Conversación abierta','Casa Oliva','Identidad y web','3.800 €','CO'],['Propuesta enviada','Estudio Norte','Proyecto de interiorismo','8.400 €','EN'],['Próximo paso','Taller Forma','Acompañamiento mensual','2.100 €','TF']].map(([stage,company,detail,value,initials],i)=><div className="mkt-lane" key={stage}><p><span style={{background:['#8b7bec','#4a8fed','#20ae90'][i]}}/>{stage}<b>1</b></p><article><span className={`mkt-client-avatar avatar-${i}`}>{initials}</span><h4>{company}</h4><p>{detail}</p><strong>{value}</strong><div><Icon name="clock"/> {i===1?'Pendiente de respuesta':'Revisar esta semana'}</div></article></div>)}</div>:view==='Seguimientos'?<div className="mkt-demo-task"><span className="mkt-icon-box"><Icon name="clock"/></span><div><h4>Un presupuesto pendiente, una acción concreta.</h4><p>Prepara una tarea para revisar la propuesta de Estudio Norte.</p>{followup?<p className="mkt-success" role="status">✓ Tarea de ejemplo creada: revisar propuesta de Estudio Norte.</p>:null}</div><button className="mkt-button" disabled={followup} onClick={()=>setFollowup(true)}>{followup?'Seguimiento creado':'Crear seguimiento de ejemplo'}</button></div>:<div className="mkt-demo-task"><span className="mkt-icon-box"><Icon name="spark"/></span><div><h4>{selected===0?'Los borradores con IA empiezan en Pro.':'Un punto de partida para retomar la conversación.'}</h4><p>{selected===0?'Explora Pro para ver un ejemplo. El resto de la gestión comercial sigue disponible en Starter.':'Borrador de ejemplo para revisión humana; esta demo no consulta un servicio de IA.'}</p>{draft&&selected>0?<blockquote role="status">Hola, Ana. ¿Has podido revisar nuestra propuesta? Si te viene bien, podemos comentar las dudas y definir el siguiente paso. Quedo pendiente.</blockquote>:null}</div>{selected===0?<button className="mkt-button" onClick={()=>selectPlan(1)}>Explorar Pro <Icon/></button>:<button className="mkt-button" disabled={draft} onClick={()=>setDraft(true)}>{draft?'Ejemplo visible':'Mostrar borrador de ejemplo'}</button>}</div>}</div>
      <div className="mkt-preview-footer"><span><Icon name="shield"/> Demostración independiente de tus datos</span><Link href="/dashboard">Abrir mi CRM <Icon/></Link></div></div><p className="mkt-preview-scope"><strong>Hoja de ruta {plan.name}:</strong> {plan.future}. Estas funciones están previstas y no se presentan como disponibles hoy.</p></section>
    <section className="mkt-pricing" id="planes"><div className="mkt-container"><div className="mkt-centered-heading"><p className="mkt-eyebrow">ESPACIO PARA TU PRÓXIMA ETAPA</p><h2>Un plan para empezar.<br/>Capacidad para seguir.</h2><p>Elige el alcance que encaja con tu equipo.</p></div><div className="mkt-pricing-controls"><div className="mkt-period" role="group" aria-label="Periodo de precios"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Mensual</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Anual</button></div><span>Precios orientativos de la propuesta comercial</span></div><div className="mkt-pricing-grid">{plans.map((p,i)=><article className={`mkt-price-card ${i===1?'mkt-price-featured':''}`} key={p.name}>{i===1?<span className="mkt-price-ribbon">PARA EQUIPOS QUE QUIEREN IR MÁS ALLÁ</span>:null}<p className="mkt-price-name">{p.name}</p><p className="mkt-price-tag">{p.tag}</p><div className="mkt-price"><strong>{money(p.price*(annual?12:1))}</strong><span>/ persona<br/>/ {annual?'año':'mes'}</span></div><p className="mkt-price-description">{p.description}</p><button className={`mkt-button ${i===1?'':'mkt-button-outline'}`} onClick={()=>selectPlan(i,true)}>Explorar {p.name} <Icon/></button><ul>{p.features.map(f=><li key={f}><Icon name="check"/>{f}</li>)}<li><Icon name="check"/>{p.messages}{i===3?'':' mensajes / mes'}</li></ul><p className="mkt-planned">Previsto: {p.future.toLowerCase()}.</p></article>)}</div><p className="mkt-price-disclaimer">Tarifas de referencia, sin contratación activa. El cálculo anual equivale a 12 mensualidades, sin descuento aplicado. Impuestos, condiciones y alcance definitivo se definirán antes del lanzamiento. Los límites operativos y costes de proveedores se revisarán por separado.</p>
      <div className="mkt-estimator"><div><p className="mkt-eyebrow">HAZTE UNA IDEA</p><h3>Calcula el tamaño de tu próximo paso.</h3><p>Estimación del plan {plan.name}. Puedes cambiarlo en la demo o desde las tarjetas.</p></div><div className="mkt-seat-control"><label htmlFor="mkt-seats">Personas en el equipo</label><div><button aria-label="Quitar una licencia" disabled={seats<=1} onClick={()=>setSeats(n=>Math.max(1,n-1))}>−</button><input id="mkt-seats" type="number" min="1" max={plan.max} value={seats} onChange={e=>setSeats(Math.max(1,Math.min(plan.max,Math.trunc(Number(e.target.value)||1))))}/><button aria-label="Añadir una licencia" disabled={seats>=plan.max} onClick={()=>setSeats(n=>Math.min(plan.max,n+1))}>+</button></div></div><div className="mkt-estimate-total" aria-live="polite"><strong>{money(plan.price*seats*(annual?12:1))}</strong><span>/ {annual?'año':'mes'} · estimación</span></div></div>
    </div></section>
    <section className="mkt-security mkt-container" id="seguridad"><div className="mkt-security-visual"><div className="mkt-security-orbit"/><div className="mkt-shield"><Icon name="shield"/></div><span className="mkt-security-label label-one">Acceso por roles</span><span className="mkt-security-label label-two">Sesiones revocables</span><span className="mkt-security-label label-three">Datos por empresa</span></div><div><p className="mkt-eyebrow">LA CONFIANZA TAMBIÉN SE CONSTRUYE POR DENTRO</p><h2>Tu información.<br/>Con límites claros.</h2><p>Separación de datos entre empresas, permisos comprobados en el servidor y registro de acciones para revisar lo que ocurre.</p><ul><li><Icon name="check"/>Contraseñas protegidas y control de sesiones.</li><li><Icon name="check"/>Credenciales de proveedores cifradas.</li><li><Icon name="check"/>Auditoría y comprobaciones automatizadas.</li></ul><small>La revisión de seguridad de producción y la validación legal siguen pendientes. No se anuncia una certificación de cumplimiento.</small></div></section>
    <section className="mkt-faq mkt-container" id="preguntas"><div><p className="mkt-eyebrow">ANTES DE DAR EL SIGUIENTE PASO</p><h2>Las cosas claras.</h2><p>Lo que puedes explorar hoy y lo que vendrá con el lanzamiento.</p></div><div>{[
      ['¿Puedo probar cómo cambia el CRM entre planes?','Sí. En la demo puedes alternar los cuatro planes, consultar sus cupos y probar un seguimiento o un borrador ilustrativo. Es una simulación separada del CRM y no cambia tu suscripción.'],
      ['¿Ya se puede contratar Revenia?','Todavía no. Esta web es la presentación local previa al lanzamiento. Los precios son orientativos y no hay cobros ni formularios de contratación activos.'],
      ['¿Los mensajes y la IA funcionan en esta demostración?','La demo utiliza ejemplos locales. El CRM tiene adaptadores y motores implementados, pero conectar cuentas reales, validar cada proveedor y habilitar sus operaciones forma parte de la preparación del lanzamiento.'],
      ['¿Sustituye a mi gestoría o a un programa fiscal certificado?','No. Revenia organiza la gestión comercial y el seguimiento de facturas. El alcance fiscal, la factura electrónica y cualquier certificación deben definirse y validarse antes del lanzamiento.'],
      ['¿Qué comparten los planes?','La organización de clientes, oportunidades, presupuestos y tareas. La propuesta diferencia la capacidad de mensajería, las licencias y el acceso a borradores de IA. Las funciones futuras aparecen indicadas expresamente.'],
      ['¿Se incluyen firma digital, SSO e informes a medida?','Figuran en la hoja de ruta, pero todavía no están disponibles. Antes de contratar se deberá confirmar el alcance final de cada plan.'],
    ].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="mkt-final-cta"><div className="mkt-container"><p className="mkt-eyebrow">DA EL SIGUIENTE PASO CON REVENIA</p><h2>Tu equipo tiene mejores<br/>cosas que perseguir facturas.</h2><div className="mkt-actions"><a href="#demo" className="mkt-button mkt-button-white">Explorar Revenia <Icon/></a><Link href="/dashboard" className="mkt-button mkt-button-glass">Entrar en mi CRM</Link></div><p>Conoce el producto hoy. Decide con toda la información.</p></div></section>
    </main><footer className="mkt-footer mkt-container"><div><a href="#" aria-label="Revenia, volver al inicio"><Brand/></a><p>Ventas, facturas y seguimiento conectados.</p></div><nav aria-label="Enlaces del pie"><a href="#producto">Producto</a><a href="#planes">Planes</a><a href="#preguntas">Preguntas frecuentes</a><Link href="/login">Acceso al CRM</Link></nav><div className="mkt-footer-bottom"><span>© 2026 Revenia · Presentación previa al lanzamiento</span><span>Información legal y condiciones comerciales en preparación.</span></div></footer>
  </div>;
}
