"use client";

import {FormEvent, useState} from "react";

export function PlanCheckout({plan,price}:{plan:string;price:string}){
  const options=[['Starter','29'],['Pro','79'],['Business','149'],['Enterprise','299']] as const;
  const [chosenPlan,setChosenPlan]=useState(plan);
  const chosenPrice=options.find(([name])=>name===chosenPlan)?.[1]??price;
  const [sent,setSent]=useState(false);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSent(true);}
  return <section className="mkt-checkout" aria-labelledby="checkout-title"><div className="mkt-checkout-intro"><p className="mkt-eyebrow">SIGUIENTE PASO</p><h3 id="checkout-title">Prepara el alta de tu empresa</h3><p>Elige el plan y completa los datos de facturación. El precio se calcula por empresa y se muestra antes de continuar.</p><div className="mkt-checkout-selected"><span>Plan elegido</span><strong>{chosenPlan}</strong><b>{chosenPrice} € / mes</b></div><small>El pago real se habilitará al conectar el proveedor de pagos y publicar las condiciones definitivas.</small></div><form onSubmit={submit}><div className="mkt-checkout-grid"><label>Plan y precio<select name="plan" value={chosenPlan} onChange={event=>{setChosenPlan(event.target.value);setSent(false);}} required>{options.map(([name,value])=><option key={name} value={name}>{name} · {value} € / mes por empresa</option>)}</select></label><label>Nombre legal de la empresa<input name="company" required placeholder="Empresa S.L."/></label><label>NIF / CIF<input name="taxId" required placeholder="B12345678"/></label><label>Persona responsable<input name="contact" required placeholder="Nombre y apellidos"/></label><label>Correo de facturación<input name="billingEmail" type="email" required placeholder="facturacion@empresa.com"/></label><label>Dirección fiscal<input name="address" required placeholder="Calle, número, ciudad"/></label><label>País<select name="country" defaultValue="ES" required><option value="ES">España</option><option value="PT">Portugal</option><option value="FR">Francia</option><option value="OTHER">Otro país</option></select></label></div><label className="mkt-checkout-check"><input type="checkbox" required/> He leído y acepto las condiciones del servicio y la política de privacidad.</label><label className="mkt-checkout-check"><input type="checkbox" required/> Confirmo que los datos de facturación son correctos y autorizo el contacto comercial relacionado con el alta.</label><button className="mkt-button" type="submit">Continuar a pago seguro <span>→</span></button>{sent?<p className="mkt-checkout-success" role="status">Datos preparados correctamente. Falta conectar el proveedor de pago para completar el cobro.</p>:null}</form></section>;
}
