import Link from 'next/link';
import {AuditVerificationPanel} from '@/components/audit-verification';
import {SubmitButton} from '@/components/submit-button';import {PageFeedback} from '@/components/page-feedback';
import {requireSession} from '@/lib/auth/current-session';import {securityOverview} from '@/lib/security-center/service';import {summarize} from '@/lib/security-center/checks';import {scanSecurityAction,updateFindingAction} from '@/app/security-actions';
const states:Record<string,string>={open:'Abierto',in_progress:'En corrección',pending_verification:'Por verificar',resolved:'Resuelto por comprobación',accepted:'Riesgo aceptado'};
const checkStates={pass:'Superado',fail:'Requiere atención',not_evaluated:'Sin evaluar'};
export default async function SecurityPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const session=await requireSession();const [data,q]=await Promise.all([securityOverview(session),searchParams]);const latest=data.runs[0];const counts=summarize(latest?.results??[]);
 return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">SECURITY CENTER</p><h1>Seguridad con evidencia</h1><p>Comprobaciones de tu entorno, hallazgos y seguimiento de las correcciones.</p></div><form action={scanSecurityAction}><SubmitButton>Ejecutar comprobación</SubmitButton></form></header>
 <PageFeedback error={q.error} success={q.analizado?'Comprobación terminada. Revisa su alcance y los controles sin evaluar.':q.guardado?'Seguimiento actualizado.':undefined}/>
 <section className="metrics-grid">{[[counts.passed,'Controles superados'],[counts.failed,'Requieren atención'],[counts.notEvaluated,'Sin evaluar'],[data.findings.filter(x=>x.status!=='resolved').length,'Hallazgos pendientes']].map(([n,label])=><article className="panel" key={label}><p>{label}</p><h2>{n}</h2></article>)}</section>
 <article className="panel"><h2>{latest?'Última comprobación':'Todavía no hay comprobaciones'}</h2><p>{latest?latest.started_at.toLocaleString('es-ES')+' · '+(latest.status==='completed'?'Terminada':latest.status==='failed'?'Fallida':'En curso')+' · reglas '+latest.rules_version:'Ejecuta una revisión para obtener resultados reales. No se presupone que ningún control haya pasado.'}</p><p>{latest?.scope??'El scanner está limitado al origen local configurado. No admite direcciones arbitrarias ni analiza sistemas de terceros.'}</p><p>Los resultados son una fotografía del momento indicado; no acreditan ausencia de vulnerabilidades.</p><div className="button-row"><Link href="/api/v1/security/report" className="secondary-button button-link" target="_blank">Exportar informe JSON</Link><Link href="/api-docs" className="secondary-button button-link">Consultar API</Link><Link href="/laboratorio" className="secondary-button button-link">Guía del laboratorio</Link></div></article>
 {latest?<article className="panel table-scroll"><h2>Controles evaluados</h2><table><thead><tr><th>Control</th><th>Resultado</th><th>Evidencia</th></tr></thead><tbody>{latest.results.map(r=><tr key={r.id}><td><strong>{r.title}</strong><p className="helper-text">{r.id}</p></td><td><span className={'badge'+(r.status==='pass'?' success':'')}>{checkStates[r.status]}</span></td><td>{r.evidence}</td></tr>)}</tbody></table></article>:null}
 <section className="page-stack"><h2>Hallazgos y remediación</h2>{data.findings.length?data.findings.map(f=><article className="panel" key={f.id}><div className="panel-heading"><h3>{f.title}</h3><span className="badge">{f.severity} · {states[f.status]}</span></div><p>{f.evidence}</p><p><strong>Corrección:</strong> {f.remediation}</p>{f.reason?<p><strong>Justificación:</strong> {f.reason} {f.review_at?'· revisar antes del '+f.review_at.toLocaleDateString('es-ES'):''}</p>:null}{f.status!=='resolved'?<form action={updateFindingAction} className="form-grid"><input type="hidden" name="id" value={f.id}/><label>Seguimiento<select name="status" defaultValue={f.status}><option value="open">Abierto</option><option value="in_progress">En corrección</option><option value="pending_verification">Por verificar</option><option value="accepted">Aceptar riesgo temporalmente</option></select></label><label>Revisión si aceptas el riesgo<input type="date" name="reviewAt"/></label><label className="wide">Motivo y siguiente acción<textarea name="reason" minLength={12} maxLength={1000} required defaultValue={f.reason??''}/></label><div><SubmitButton>Guardar seguimiento</SubmitButton></div></form>:null}</article>):<article className="panel empty-state"><strong>{latest?'Sin hallazgos registrados':'Sin evaluar'}</strong><p>{latest?'Consulta también los controles sin evaluar y la fecha de la ejecución.':'Los hallazgos aparecerán después de una comprobación.'}</p></article>}</section>
 <article className="panel table-scroll"><h2>Historial reciente</h2><table><thead><tr><th>Fecha</th><th>Estado</th><th>Superados / evaluados</th></tr></thead><tbody>{data.runs.map(r=>{const s=summarize(r.results);return <tr key={r.id}><td>{r.started_at.toLocaleString('es-ES')}</td><td>{r.status}</td><td>{s.passed} / {s.total-s.notEvaluated}</td></tr>;})}</tbody></table></article><AuditVerificationPanel/></main>;
}

