import Link from "next/link";
import {queueDraft} from "@/app/engine-actions";
import { markInboxRead, sendMessage } from "@/app/actions";
import { PageFeedback } from "@/components/page-feedback";
import { SubmitButton } from "@/components/submit-button";
import { requireSession } from "@/lib/auth/current-session";
import { getInbox } from "@/lib/domain/operations-service";

type Query = Promise<Record<string,string|string[]|undefined>>;
const first = (value:string|string[]|undefined) => Array.isArray(value) ? value[0] : value;

export default async function InboxPage({ searchParams }: { searchParams:Query }) {
  const [session, query] = await Promise.all([requireSession(),searchParams]);
  const inbox = await getInbox(session.tenantId);
  const unread = inbox.messages.filter((message) => message.unread).length;
  return <main className="page-stack">
    <header className="page-heading"><div><p className="eyebrow">COMUNICACIONES</p><h1>Inbox</h1><p>Email y WhatsApp reunidos en una bandeja segura.</p></div><div className="header-actions">{unread > 0 ? <form action={markInboxRead}><SubmitButton className="secondary-button" pendingText="Marcando…">Marcar como leído</SubmitButton></form> : null}<Link className="primary-button button-link" href="/inbox?nuevo=1">＋ Nuevo mensaje</Link></div></header>
    <PageFeedback error={first(query.error)} success={first(query.guardado) ? "Operación registrada. Los borradores preparados siguen pendientes de autorización. Consulta el estado del mensaje." : first(query.enviado) ? "Borrador guardado en la conversación. Pendiente de envío." : first(query.leido) ? "Bandeja marcada como leída." : undefined}/>
    <p className="secure-note">Revisa cada borrador antes de autorizar el envío. Gestiona la conexión y el permiso del destinatario antes de enviar.</p><div className="header-actions"><Link href="/permisos-contacto">Permisos de contacto</Link><Link href="/ejecuciones">Estado de los envíos</Link></div><section className="inbox-layout">
      <article className="panel conversation-list"><div className="panel-toolbar"><strong>{unread} sin leer</strong><span>{inbox.messages.length} mensajes</span></div>{inbox.messages.map((message) => <Link href={`/inbox?mensaje=${message.id}`} className={`conversation-item${message.unread ? " unread" : ""}`} key={message.id}><span className="avatar">{message.client?.split(" ").map((part) => part[0]).join("").slice(0,2) ?? "R"}</span><div><strong>{message.client ?? "Conversación general"}</strong><small>{message.company ?? "NovaTech"} · {message.channel}</small><p>{message.body}</p></div><time>{message.createdAt}</time></Link>)}</article>
      <article className="panel conversation-preview"><p className="eyebrow">CONVERSACIÓN</p>{(() => { const selected=inbox.messages.find((message)=>message.id===first(query.mensaje)) ?? inbox.messages[0]; return selected ? <><h2>{selected.client ?? "Conversación general"}</h2><p className="message-meta">{selected.channel} · {selected.createdAt} · {selected.direction === "Salida" ? selected.delivery_status : "Recibido"}</p><p>{selected.sender_address}</p><strong>{selected.subject}</strong><div className={`message-bubble ${selected.direction === "Salida" ? "outgoing" : "incoming"}`}>{selected.body}</div>{selected.direction === "Salida" && selected.delivery_status === "draft" ? <form action={queueDraft} className="form-grid"><input type="hidden" name="id" value={selected.id}/>{selected.channel === "WhatsApp" ? <><p className="helper-text wide">WhatsApp enviará la plantilla aprobada en Meta que indiques; el texto del borrador no se envía. Esta versión admite plantillas sin parámetros.</p><label>Plantilla aprobada<input name="template" required pattern="[a-z0-9_]{1,100}"/></label><label>Idioma<input name="language" required defaultValue="es" pattern="[a-z]{2}(_[A-Z]{2})?"/></label></> : null}<label className="check-row wide"><input name="confirm" type="checkbox" required/> He revisado el destinatario y autorizo este envío.</label><div className="form-footer wide"><SubmitButton>Autorizar envío</SubmitButton></div></form> : null}<Link href={`/inbox?nuevo=1&cliente=${selected.client_id ?? ""}`} className="primary-button button-link">Responder</Link></> : <div className="empty-state"><strong>Sin conversaciones</strong><span>Envía el primer mensaje desde el botón superior.</span></div>; })()}</article>
    </section>
    {first(query.nuevo)==="1" ? <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="eyebrow">COMUNICACIÓN SEGURA</p><h2>Nuevo mensaje</h2></div><Link href="/inbox" className="icon-button">×</Link></div><form action={sendMessage} className="form-grid"><label className="wide">Cliente<select name="clientId" defaultValue={first(query.cliente) ?? ""} required><option value="" disabled>Selecciona un cliente</option>{inbox.clients.map((client)=><option key={client.id} value={client.id}>{client.name} · {client.company}</option>)}</select></label><label>Canal<select name="channel"><option>WhatsApp</option><option>Email</option></select></label><label className="wide">Asunto<input name="subject" defaultValue="Seguimiento comercial" maxLength={200} required/></label><label className="wide">Mensaje<textarea name="body" minLength={1} maxLength={4000} rows={6} required autoFocus/></label><div className="form-footer wide"><Link href="/inbox" className="secondary-button button-link">Cancelar</Link><SubmitButton pendingText="Guardando…">Guardar borrador</SubmitButton></div></form></section></div> : null}
  </main>;
}
